name: xarray_cb
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - numpy
  - xarray
  - matplotlib
  - metpy
  - cartopy
  - dask
  - zarr
  - pandas
  - seaborn
  - pip
  - pip:
      - sphinx-pythia-theme