name: xarray-cb
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter-book
  - jupyterlab
  - matplotlib
  - cartopy
  - dask
  - zarr
  - pandas
  - jupyter_server<2
  - numpy
  - xarray
  - metpy
  - seaborn
  - imageio
  - netCDF4
  - pip
  - pip:
    - sphinx-pythia-theme
    
